[package]
name = "ray_tracing"
version = "0.1.0"
authors = ["Dmarcano <dmarcan1@swarthmore.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
image = "0.23"
sdl2 = "0.34.3"
